#!/bin/bash

ROOTDIR=$(dirname $0)
source $ROOTDIR/venv/bin/activate

[ -f $ROOTDIR/.env ] && source $ROOTDIR/.env

usage() {
    echo "Usage: $(basename $0): [-h] [command and arguments]"
}

if [ "$1" = -h ]; then
    usage
    exit 0
fi

if [ "$1" ]; then
    "$@"
else
    ADDPS1='(pingtest) ' bash
fi
